// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxS83BAVKD4YH-5Hb0N1DpaYvMu-SR8Y4',
    appId: '1:670582885866:web:0bfd3f7cd59bd766a2b693',
    messagingSenderId: '670582885866',
    projectId: 'attendance-applicationn',
    authDomain: 'attendance-applicationn.firebaseapp.com',
    storageBucket: 'attendance-applicationn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmV4fAgC7B0Q0D1zlx-SsEy7XQArQhYBc',
    appId: '1:670582885866:android:bfbd51ee71296070a2b693',
    messagingSenderId: '670582885866',
    projectId: 'attendance-applicationn',
    storageBucket: 'attendance-applicationn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARY8mwToYkGIfOdkvCwcEuaoIGklHljO8',
    appId: '1:670582885866:ios:12b86067679ecf87a2b693',
    messagingSenderId: '670582885866',
    projectId: 'attendance-applicationn',
    storageBucket: 'attendance-applicationn.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARY8mwToYkGIfOdkvCwcEuaoIGklHljO8',
    appId: '1:670582885866:ios:12b86067679ecf87a2b693',
    messagingSenderId: '670582885866',
    projectId: 'attendance-applicationn',
    storageBucket: 'attendance-applicationn.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxS83BAVKD4YH-5Hb0N1DpaYvMu-SR8Y4',
    appId: '1:670582885866:web:d4c99af74e57340ca2b693',
    messagingSenderId: '670582885866',
    projectId: 'attendance-applicationn',
    authDomain: 'attendance-applicationn.firebaseapp.com',
    storageBucket: 'attendance-applicationn.firebasestorage.app',
  );
}
